#######################################################
# 
# Interface1.py
# Python implementation of the Interface Interface1
# Generated by Enterprise Architect
# Created on:      04-мар-2019 0:36:43
# 
#######################################################


class Interface1:
    pass