#######################################################
# 
# LineStyle.py
# Python implementation of the Class LineStyle
# Generated by Enterprise Architect
# Created on:      04-мар-2019 0:36:43
# Original author: Lenovo-PC
# 
#######################################################
from RootModel.Model.DrawingContext import DrawingContext

class LineStyle:
    m_DrawingContext= DrawingContext()
