#######################################################
# 
# DrawingContext.py
# Python implementation of the Class DrawingContext
# Generated by Enterprise Architect
# Created on:      04-мар-2019 0:36:43
# Original author: Lenovo-PC
# 
#######################################################


class DrawingContext:
    def draw_arc(params):
        pass

    def draw_ellipse(params):
        pass

    def draw_point(Point):
        pass

    def draw_rectangle(Point):
        pass

    def draw_segment(Point):
        pass

    def __free():
        pass

    def __lock():
        pass