#######################################################
# 
# Ellipse.py
# Python implementation of the Class Ellipse
# Generated by Enterprise Architect
# Created on:      04-���-2019 0:36:43
# Original author: Lenovo-PC
# 
#######################################################
from .Shape import Shape

class Ellipse(Shape):
    def draw(DrawingContext):
        pass