#######################################################
# 
# Ellipse.py
# Python implementation of the Class Ellipse
# Generated by Enterprise Architect
# Created on:      04-���-2019 0:36:43
# Original author: Lenovo-PC
# 
#######################################################
from .Shape import Shape
from .DrawingContext import DrawingContext


class Ellipse(Shape):
    def draw(self, context: DrawingContext):
        a, b, c, d = *self.begin.get_coordinates(), *self.end.get_coordinates()
        context.draw_ellipse((a, b, c, d))