#######################################################
# 
# Ellipse.py
# Python implementation of the Class Ellipse
# Generated by Enterprise Architect
# Created on:      04-мар-2019 0:36:43
# Original author: Lenovo-PC
# 
#######################################################
from RootModel.Model.PlaneShape import PlaneShape
from RootModel.Model.Shape import Shape
from RootModel.Model.SmoothShape import SmoothShape

class Ellipse(PlaneShape, Shape, SmoothShape):
    def draw(DrawingContext):
        pass