#######################################################
# 
# FlatShape.py
# Python implementation of the Class FlatShape
# Generated by Enterprise Architect
# Created on:      04-мар-2019 0:36:43
# Original author: Lenovo-PC
# 
#######################################################


class FlatShape:
    pass