#######################################################
# 
# LineShape.py
# Python implementation of the Class LineShape
# Generated by Enterprise Architect
# Created on:      04-мар-2019 0:36:43
# Original author: Lenovo-PC
# 
#######################################################
from RootModel.Model.Point2D import Point2D
from RootModel.Model.Shape import Shape

class LineShape(Shape):
    def draw(DrawingContext):
        pass

    def get_begin():
        pass

    def get_end():
        pass

    def set_begin(Point):
        pass

    def set_end(Point):
        pass