#######################################################
# 
# NIrregularPolygon.py
# Python implementation of the Class NIrregularPolygon
# Generated by Enterprise Architect
# Created on:      04-мар-2019 0:36:43
# Original author: Lenovo-PC
# 
#######################################################
from RootModel.Model.PolygonalShape import PolygonalShape

class NIrregularPolygon(PolygonalShape):
    pass