#######################################################
# 
# NRegularPolygon.py
# Python implementation of the Class NRegularPolygon
# Generated by Enterprise Architect
# Created on:      04-���-2019 0:36:43
# Original author: Lenovo-PC
# 
#######################################################
from .PolygonalShape import PolygonalShape

class NRegularPolygon(PolygonalShape):
    def draw(DrawingContext):
        pass

    def set_vertex_count(vertex_count):
        pass