#######################################################
# 
# Parallelogram.py
# Python implementation of the Class Parallelogram
# Generated by Enterprise Architect
# Created on:      04-���-2019 0:36:43
# Original author: Lenovo-PC
# 
#######################################################
from .PolygonalShape import PolygonalShape

class Parallelogram(PolygonalShape):
    __vertex_count = 3
    def draw(DrawingContext):
        pass