#######################################################
# 
# Parallelogram.py
# Python implementation of the Class Parallelogram
# Generated by Enterprise Architect
# Created on:      04-мар-2019 0:36:43
# Original author: Lenovo-PC
# 
#######################################################
from RootModel.Model.NIrregularPolygon import NIrregularPolygon
from RootModel.Model.PolygonalShape import PolygonalShape

class Parallelogram(NIrregularPolygon, PolygonalShape):
    __vertex_count = 3
    def draw(DrawingContext):
        pass