#######################################################
# 
# PlaneShape.py
# Python implementation of the Class PlaneShape
# Generated by Enterprise Architect
# Created on:      04-мар-2019 0:36:43
# Original author: Lenovo-PC
# 
#######################################################
from RootModel.Model.Shape import Shape

class PlaneShape(Shape):
    pass