#######################################################
# 
# Point2D.py
# Python implementation of the Class Point2D
# Generated by Enterprise Architect
# Created on:      04-мар-2019 0:36:43
# Original author: Lenovo-PC
# 
#######################################################


class Point2D:
    def get_coordinates():
        pass

    def set_coordinates(x = NULL, y = NULL):
        pass