#######################################################
# 
# PolygonalLine.py
# Python implementation of the Class PolygonalLine
# Generated by Enterprise Architect
# Created on:      04-мар-2019 0:36:43
# Original author: Lenovo-PC
# 
#######################################################
from RootModel.Model.LineShape import LineShape

class PolygonalLine:
    m_LineShape= LineShape()

    def draw(DrawingContext):
        pass