#######################################################
# 
# PolygonalShape.py
# Python implementation of the Class PolygonalShape
# Generated by Enterprise Architect
# Created on:      04-���-2019 0:36:43
# Original author: Lenovo-PC
# 
#######################################################
from .Shape import Shape
from .DrawingContext import DrawingContext

class PolygonalShape(Shape):
    def draw(context: DrawingContext) -> None:
        pass