#######################################################
# 
# PolygonalShape.py
# Python implementation of the Class PolygonalShape
# Generated by Enterprise Architect
# Created on:      04-мар-2019 0:36:43
# Original author: Lenovo-PC
# 
#######################################################
from RootModel.Model.PlaneShape import PlaneShape
from RootModel.Model.Shape import Shape

class PolygonalShape(PlaneShape, Shape):
    def draw():
        pass