#######################################################
# 
# QTDrawingContext.py
# Python implementation of the Class QTDrawingContext
# Generated by Enterprise Architect
# Created on:      04-мар-2019 0:36:43
# Original author: Lenovo-PC
# 
#######################################################
from RootModel.Model.DrawingContext import DrawingContext

class QTDrawingContext(DrawingContext):
    def draw_arc(params):
        pass

    def draw_ellipse(params):
        pass

    def draw_point(Point):
        pass

    def draw_rectangle(Point):
        pass

    def draw_segment(Point):
        pass

    def set_color(color):
        pass

    def set_line_style(style):
        pass