#######################################################
# 
# Rhombus.py
# Python implementation of the Class Rhombus
# Generated by Enterprise Architect
# Created on:      04-���-2019 0:36:43
# Original author: Lenovo-PC
# 
#######################################################
from .Parallelogram import Parallelogram

class Rhombus(Parallelogram):
    __vertex_count = 2
    def draw(DrawingContext):
        pass