#######################################################
# 
# Segment.py
# Python implementation of the Class Segment
# Generated by Enterprise Architect
# Created on:      04-мар-2019 0:36:43
# Original author: Lenovo-PC
# 
#######################################################
from RootModel.Model.LineShape import LineShape

class Segment(LineShape):
    def draw(DrawingContext):
        pass