#######################################################
# 
# Shape.py
# Python implementation of the Class Shape
# Generated by Enterprise Architect
# Created on:      04-мар-2019 0:36:43
# Original author: Lenovo-PC
# 
#######################################################
from RootModel.Model.DrawingContext import DrawingContext
from RootModel.Model.Point2D import Point2D

class Shape:
    m_DrawingContext= DrawingContext()

    m_Point2D= Point2D()

    def draw(DrawingContext):
        pass

    def location():
        pass

    def move(target_location):
        pass