#######################################################
# 
# SymmetricShape.py
# Python implementation of the Class SymmetricShape
# Generated by Enterprise Architect
# Created on:      04-мар-2019 0:36:43
# Original author: Lenovo-PC
# 
#######################################################
from RootModel.Model.PlaneShape import PlaneShape

class SymmetricShape(PlaneShape):
    pass