#######################################################
# 
# ThreeDimensionalShape.py
# Python implementation of the Class ThreeDimensionalShape
# Generated by Enterprise Architect
# Created on:      04-мар-2019 0:36:44
# Original author: Lenovo-PC
# 
#######################################################
from RootModel.Model.Shape import Shape

class ThreeDimensionalShape(Shape):
    pass