#######################################################
# 
# Triangle.py
# Python implementation of the Class Triangle
# Generated by Enterprise Architect
# Created on:      04-мар-2019 0:36:44
# Original author: Lenovo-PC
# 
#######################################################
from RootModel.Model.NIrregularPolygon import NIrregularPolygon

class Triangle(NIrregularPolygon):
    __vertex_count = 3
    def draw(DrawingContext):
        pass